abstract type LoKIFile end
abstract type Output end
abstract type RelError end
abstract type SmartGrid end
abstract type EnergyGrid end
abstract type ODESetParameters end
abstract type NonLinearRoutines end
abstract type Numerics end
abstract type Gui end
abstract type StateProperties end
abstract type GasProperties end
abstract type ElectronKinectics end
abstract type WorkingConditions end